=== Serra-albarregas/xml/XSD/agenda.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="agenda">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="contacto" minOccurs="1" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
<xs:element name="contacto">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="nombre" minOccurs="1" maxOccurs="1"></xs:element>
            <xs:element ref="apellidos" minOccurs="1" maxOccurs="1"></xs:element>
            <xs:element ref="movil" minOccurs="0" maxOccurs="unbounded"></xs:element>
            <xs:element ref="fijo" minOccurs="0" maxOccurs="unbounded"></xs:element>
            <xs:element ref="email" minOccurs="0" maxOccurs="1"></xs:element>
            <xs:element ref="genero" minOccurs="0" maxOccurs="1"></xs:element>
            <xs:element ref="pareja" minOccurs="0" maxOccurs="1"></xs:element>
            <xs:element ref="comentario" minOccurs="1" maxOccurs="1"></xs:element>
        </xs:sequence>
        <xs:attribute ref="codigo"></xs:attribute>
    </xs:complexType>
</xs:element>

<xs:element name="nombre" type="xs:string"></xs:element>
<xs:element name="apellidos" type="xs:string"></xs:element>

<xs:element name="movil">
    <xs:complexType>
        <xs:simpleContent>
            <xs:extension base="movil-type">
                <xs:attribute ref="empresa"></xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:element>

<xs:element name="fijo">
    <xs:simpleType>
        <xs:restriction base="xs:int">
            <xs:pattern value="[0-9]{9}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
</xs:element>

<xs:element name="email">
    <xs:complexType>
        <xs:simpleContent>
            <xs:extension base="email-type">
                <xs:attribute ref="tipo"></xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:element>

<xs:element name="genero">
    <xs:complexType>
        <xs:choice>
            <xs:element name="hombre"></xs:element>
            <xs:element name="mujer"></xs:element>
        </xs:choice>
    </xs:complexType>
</xs:element>

<xs:element name="pareja">
    <xs:complexType>
        <xs:attribute name="codigo" type="xs:IDREF"></xs:attribute>
    </xs:complexType>
</xs:element>

<xs:element name="comentario" type="xs:string"></xs:element>

<!-- ATRIBUTOS -->
<xs:attribute name="codigo">
    <xs:simpleType>
        <xs:restriction base="xs:ID">
            <xs:pattern value="c[0-9]+"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
</xs:attribute>

<xs:attribute name="empresa" type="xs:string"></xs:attribute>

<xs:attribute name="tipo">
    <xs:simpleType>
        <xs:restriction base="xs:string">
            <xs:enumeration value="personal"></xs:enumeration>
            <xs:enumeration value="empresa"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
</xs:attribute>

<!-- TIPOS DE DATOS -->
<xs:simpleType name="movil-type">
    <xs:restriction base="xs:int">
        <xs:pattern value="[0-9]{9}"></xs:pattern>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="email-type">
    <xs:restriction base="xs:string">
        <xs:pattern value="[^@]+@[^@]+\.(com|es)"></xs:pattern>
    </xs:restriction>
</xs:simpleType>

</xs:schema>

=== Serra-albarregas/xml/XSD/agenda.xml
<?xml version="1.0" encoding="UTF-8"?>

<agenda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="agenda.xsd">
    <contacto codigo="c1">
        <nombre>Mauricio</nombre>
        <apellidos>Hidalgo</apellidos>
        <movil empresa="Vodafone">654652562</movil>
        <movil>695656265</movil>
        <fijo>927545152</fijo>
        <email tipo="empresa">mauri@gmail.com</email>
        <genero>
            <hombre/>
        </genero>
        <pareja codigo="c2"/>
        <comentario>Un buen tipo</comentario>
    </contacto>
    <contacto codigo="c2">
        <nombre>Fernando</nombre>
        <apellidos>Navarro</apellidos>
        <fijo>927215121</fijo>
        <fijo>927545152</fijo>
        <email tipo="personal">fernandoabogado@gmail.com</email>
        <genero>
            <hombre />
        </genero>
        <pareja codigo="c1"/>
        <comentario>Abogado</comentario>
    </contacto>
    <contacto codigo="c3">
        <nombre>Belén</nombre>
        <apellidos>López</apellidos>
        <comentario>Del montón bueno</comentario>
    </contacto>
</agenda>
